import { Destination, Service, Testimonial, JournalPost, TeamMember, FeaturedJourney } from "./types";

export const destinations: Destination[] = [
  {
    slug: "santorini",
    name: "Santorini",
    region: "Europe",
    tagline: "Where the Aegean Meets the Sky",
    description: "Whitewashed villages perched on volcanic cliffs, sunsets that paint the caldera in gold and amber, and a quietude that only the most discerning travellers will find.",
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
    featured: true,
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    region: "Asia",
    tagline: "Temples, Tea & Timelessness",
    description: "Ancient temples shrouded in morning mist, private tea ceremonies in hidden gardens, and the gentle rustle of bamboo groves — Kyoto reveals itself slowly to those who linger.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    featured: true,
  },
  {
    slug: "amalfi-coast",
    name: "Amalfi Coast",
    region: "Europe",
    tagline: "La Dolce Vita, Perfected",
    description: "Terraced lemon groves cascading to cerulean waters, intimate trattorias where the pasta is made by hand, and coastal roads that wind through some of Italy's most breathtaking scenery.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=1200&q=80",
    featured: true,
  },
  {
    slug: "patagonia",
    name: "Patagonia",
    region: "South America",
    tagline: "The Edge of the Earth",
    description: "Jagged granite spires rising from pristine wilderness, glacial lakes of impossible blue, and a silence so complete it becomes its own kind of luxury.",
    image: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=1200&q=80",
    featured: true,
  },
  {
    slug: "maldives",
    name: "Maldives",
    region: "Indian Ocean",
    tagline: "Paradise, Reimagined",
    description: "Overwater villas suspended above crystalline lagoons, private sandbanks accessible only by seaplane, and marine life so abundant the reef becomes your living room.",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&q=80",
    featured: true,
  },
  {
    slug: "marrakech",
    name: "Marrakech",
    region: "Africa",
    tagline: "A Sensory Tapestry",
    description: "Behind unassuming doors lie palatial riads with mosaic courtyards, rooftop terraces overlooking the Atlas Mountains, and souks that tell stories in saffron and silk.",
    image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1200&q=80",
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    region: "Oceania",
    tagline: "Nature's Masterwork",
    description: "From fjords carved by glaciers to geothermal wonderlands, New Zealand offers an unparalleled canvas of natural beauty paired with world-class lodges and vineyard estates.",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80",
  },
  {
    slug: "costa-rica",
    name: "Costa Rica",
    region: "Central America",
    tagline: "Pura Vida in Luxury",
    description: "Cloud forests alive with toucans and orchids, volcanic hot springs nestled in the jungle, and eco-lodges where sustainability meets five-star comfort.",
    image: "https://images.unsplash.com/photo-1518259102261-b57b7f63aa5a?w=1200&q=80",
  },
  {
    slug: "iceland",
    name: "Iceland",
    region: "Europe",
    tagline: "Fire, Ice & Wonder",
    description: "Where glaciers meet volcanic landscapes, the Northern Lights dance above geothermal pools, and every winding road reveals a waterfall more dramatic than the last.",
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=1200&q=80",
  },
];

export const services: Service[] = [
  {
    title: "Bespoke Itineraries",
    description: "Every journey begins with a conversation. We craft detailed, day-by-day itineraries tailored to your pace, passions, and preferences — from private museum viewings to tables at impossible-to-book restaurants.",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80",
    features: ["Personalised day-by-day planning", "Access to exclusive experiences", "Flexible pacing & preferences", "24/7 concierge support"],
  },
  {
    title: "Luxury Accommodation",
    description: "We maintain relationships with the world's finest hotels, private villas, and boutique properties. Our preferred partner status ensures upgrades, amenities, and the kind of welcome that transforms a stay into a story.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
    features: ["Preferred partner rates & upgrades", "Private villas & estates", "Boutique & heritage properties", "Suite upgrades & VIP amenities"],
  },
  {
    title: "Private Experiences",
    description: "Beyond the guidebook lie experiences that money alone cannot buy. A private dinner in a Tuscan vineyard, a dawn hot-air balloon over Cappadocia, a personal audience with a master artisan — these are the moments we curate.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80",
    features: ["Private guides & historians", "After-hours museum access", "Culinary experiences & cooking classes", "Adventure & wellness retreats"],
  },
  {
    title: "Honeymoons & Celebrations",
    description: "Whether it's a honeymoon, anniversary, or milestone birthday, we design celebrations that honour the occasion with the reverence it deserves. Every detail — from the champagne waiting in your suite to the sunset dinner on a private beach.",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
    features: ["Romantic itinerary design", "Special occasion planning", "Surprise arrangements", "Multi-generational trip coordination"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote: "Vela & Co. didn't just plan our honeymoon — they orchestrated a love letter to Italy. Every detail, from the private water taxi in Venice to the truffle hunting in Piedmont, felt like it was written just for us.",
    author: "Charlotte & James Hartley",
    location: "London, UK",
    trip: "Italian Honeymoon — 14 Days",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
  {
    id: "2",
    quote: "After twenty years of travel, I thought I'd seen it all. Then Vela arranged a private sunrise viewing of Angkor Wat followed by breakfast with a local historian. That morning changed how I see the world.",
    author: "Dr. Michael Chen",
    location: "San Francisco, USA",
    trip: "Southeast Asia — 21 Days",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    id: "3",
    quote: "Planning a family trip with three generations seemed impossible until we found Vela. They created something magical — the grandchildren still talk about the cooking class in Provence, and my mother-in-law hasn't stopped raving about the Loire Valley châteaux.",
    author: "Amara Osei-Bonsu",
    location: "Toronto, Canada",
    trip: "France Multi-Generational — 18 Days",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
  },
  {
    id: "4",
    quote: "The level of access Vela provides is extraordinary. A private after-hours tour of the Uffizi, a personal meeting with a Murano glass master, dinner on a rooftop I didn't know existed. This is travel at its finest.",
    author: "Elizabeth Waverly",
    location: "New York, USA",
    trip: "Art & Culture of Italy — 12 Days",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80",
  },
  {
    id: "5",
    quote: "We asked for adventure, and Vela delivered beyond imagination. Helicopter transfers to a glacier in New Zealand, dawn kayaking in Milford Sound, and a lodge so remote we saw more stars than we knew existed.",
    author: "Henrik & Sofia Lindström",
    location: "Stockholm, Sweden",
    trip: "New Zealand Expedition — 16 Days",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  },
];

export const journalPosts: JournalPost[] = [
  {
    slug: "art-of-slow-travel",
    title: "The Art of Slow Travel",
    excerpt: "Why the most meaningful journeys are the ones where you linger — and how slowing down reveals a destination's true character.",
    content: `There is a particular quality of light in the late afternoon in Provence that you will never see if you're racing to the next destination. It settles over the lavender fields like liquid gold, turning the stone farmhouses into something from a painting you've seen but can't quite place.\n\nThis is what slow travel offers: not just a place, but a feeling. Not just a photograph, but a memory that lives in your body — the warmth of the sun on your shoulders, the scent of wild thyme, the sound of cicadas marking time in their ancient rhythm.\n\nAt Vela & Co., we've long believed that the best travel experiences aren't measured in destinations visited but in moments truly lived. When we design an itinerary, we build in what we call "white space" — unhurried mornings, spontaneous detours, afternoons with nothing planned but the pleasure of being exactly where you are.\n\nThe art of slow travel isn't about doing less. It's about experiencing more. It's the difference between photographing a cathedral and sitting inside it long enough to watch the light move across the stone floor. It's the difference between visiting a vineyard and spending a morning with the winemaker, learning why this particular hillside produces grapes unlike any other.\n\nOur clients often tell us that their most treasured memories come from these unscripted moments — a conversation with a local shopkeeper, a wrong turn that led to a hidden beach, a rainstorm that drove them into a café where they discovered the best coffee of their lives.`,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    category: "Philosophy",
    date: "2026-06-15",
    readTime: "6 min read",
    author: "Isabella Montague",
  },
  {
    slug: "hidden-gems-japanese-ryokan",
    title: "Hidden Gems: The Japanese Ryokan",
    excerpt: "Beyond the five-star hotels lies a centuries-old tradition of hospitality that redefines what luxury means.",
    content: `The wooden door slides open with a whisper, revealing a world that exists outside of time. Your shoes are gently removed and placed aside. A woman in a perfectly pressed kimono bows and welcomes you not as a guest, but as an honoured visitor to her home.\n\nThis is the ryokan — Japan's gift to the art of hospitality, and perhaps the purest expression of luxury in the world. Not luxury as we've come to define it in the West, with its marble lobbies and crystal chandeliers, but something far more profound: the luxury of attention, of care, of centuries of tradition refined to perfection.\n\nYour room is spare by Western standards — tatami floors, a low table, a futon that will be laid out for you while you bathe. But every element has been chosen with an intentionality that borders on the sacred. The scroll in the alcove was selected for the season. The single flower arrangement captures the essence of the moment.\n\nAnd then there is the onsen. Natural hot springs, often outdoors, where you soak beneath ancient trees as steam rises around you. In winter, snow may fall gently on your shoulders while the water keeps you warm. In autumn, the maple leaves drift across the surface like nature's confetti.`,
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    category: "Destinations",
    date: "2026-05-28",
    readTime: "8 min read",
    author: "Isabella Montague",
  },
  {
    slug: "sustainable-luxury-new-frontier",
    title: "Sustainable Luxury: The New Frontier",
    excerpt: "How the world's finest properties are proving that environmental responsibility and extraordinary experiences aren't mutually exclusive.",
    content: `There was a time when "eco-lodge" conjured images of composting toilets and cold showers — a noble sacrifice of comfort for conscience. That era is over.\n\nToday's most exciting luxury properties are those that have woven sustainability into the very fabric of the guest experience, not as a compromise but as an elevation. They're proving that the most responsible choice can also be the most remarkable one.\n\nConsider Soneva Fushi in the Maldives, where the "no news, no shoes" philosophy extends to a waste-to-wealth programme that transforms the resort's waste into art, building materials, and biogas. Or Singita in East Africa, where conservation fees directly fund anti-poaching units and community development programmes.\n\nThese properties understand something fundamental: luxury and sustainability aren't opposing forces. They're natural allies. The same attention to detail, the same commitment to excellence, the same desire to create something exceptional — these values serve both pursuits.`,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80",
    category: "Sustainability",
    date: "2026-05-10",
    readTime: "7 min read",
    author: "James Beaumont",
  },
  {
    slug: "perfect-packing-art",
    title: "The Perfect Packing List: An Art Form",
    excerpt: "Our guide to travelling with elegance — what to bring, what to leave behind, and why less truly is more.",
    content: `The way you pack reveals the way you travel. Overpacking speaks to anxiety — the fear that you won't have what you need, that the world beyond your suitcase is somehow insufficient. Underpacking, done well, speaks to confidence and trust.\n\nAfter decades of helping our clients prepare for journeys across every continent, we've refined our approach to packing into something approaching an art form. The principle is simple: bring fewer things, but better things.\n\nStart with a colour palette. Not the rainbow explosion of a tourist's suitcase, but a considered selection of three or four colours that work together. Navy, cream, and a warm accent — terracotta or sage — will carry you from a morning market to an evening dinner without missing a beat.`,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=80",
    category: "Travel Tips",
    date: "2026-04-22",
    readTime: "5 min read",
    author: "James Beaumont",
  },
];

export const teamMembers: TeamMember[] = [
  {
    name: "Isabella Montague",
    role: "Founder & Lead Advisor",
    bio: "With over two decades in luxury travel, Isabella founded Vela & Co. on a simple belief: that travel, at its best, is a transformative art. A former travel editor and Virtuoso advisor, she brings an editorial eye and an unrivalled network to every journey she crafts.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
  },
  {
    name: "James Beaumont",
    role: "Senior Travel Advisor",
    bio: "James specialises in adventure and expedition travel, from Antarctic cruises to Saharan desert camps. His background in documentary filmmaking gives him an eye for the cinematic — every itinerary he designs reads like a story worth telling.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
  },
  {
    name: "Sophie Laurent",
    role: "European Specialist",
    bio: "Born in Lyon and educated in Florence, Sophie brings an insider's knowledge of Europe that no guidebook can match. From hidden bistros in Paris to private palazzo tours in Venice, her connections open doors that most travellers never know exist.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
  },
];

export const featuredJourney: FeaturedJourney = {
  slug: "amalfi-to-sicily",
  title: "The Italian Riviera",
  subtitle: "Amalfi to Sicily — A Journey Through Southern Italy's Soul",
  heroImage: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=1800&q=80",
  duration: "14 Days / 13 Nights",
  startingPrice: "From £12,500 per person",
  highlights: [
    "Private yacht transfer along the Amalfi Coast",
    "Exclusive cooking class with a Michelin-starred chef",
    "After-hours visit to Pompeii with an archaeologist",
    "Wine tasting at a 16th-century Sicilian estate",
    "Hot air balloon sunrise over the Valley of the Temples",
  ],
  description: "This is not a tour of Southern Italy. It is an immersion — a carefully choreographed journey through the landscapes, flavours, and stories that have shaped one of the world's most captivating regions. From the vertiginous beauty of the Amalfi Coast to the wild, untamed spirit of Sicily, every day reveals a new facet of Italy's southern soul.",
  itinerary: [
    { day: 1, title: "Arrival in Naples", description: "Private transfer to your clifftop suite in Ravello. Welcome dinner overlooking the Mediterranean.", image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80" },
    { day: 2, title: "Ravello & Amalfi", description: "Morning visit to Villa Cimbrone's gardens. Afternoon exploration of Amalfi with a local historian. Evening aperitivo at a hidden terrace.", image: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80" },
    { day: 3, title: "Amalfi Coast by Sea", description: "Private yacht along the coast. Stop at a secluded cove for swimming. Lunch at a waterfront restaurant in Positano accessible only by boat." },
    { day: 4, title: "Pompeii & Herculaneum", description: "After-hours private tour of Pompeii with a leading archaeologist. Afternoon visit to the lesser-known Herculaneum." },
    { day: 5, title: "Capri", description: "Day trip to Capri by private boat. Visit the Blue Grotto, explore the Gardens of Augustus, lunch at a cliffside restaurant." },
    { day: 6, title: "Journey to Puglia", description: "Scenic drive through the countryside to Puglia. Settle into a restored masseria. Evening olive oil tasting." },
    { day: 7, title: "Puglia Discoveries", description: "Morning visit to the trulli houses of Alberobello. Afternoon cooking class featuring traditional Puglian cuisine. Dinner under the stars." },
    { day: 8, title: "Matera", description: "Explore the ancient cave dwellings of Matera — a UNESCO World Heritage Site. Private lunch in a converted sassi restaurant." },
    { day: 9, title: "Journey to Sicily", description: "Flight to Catania. Private transfer to Taormina. Evening passeggiata and dinner with views of Mount Etna." },
    { day: 10, title: "Mount Etna", description: "Guided ascent of Europe's most active volcano. Wine tasting at a vineyard on Etna's slopes. Sunset dinner in Taormina." },
    { day: 11, title: "Syracuse & Ortigia", description: "Day exploring the ancient Greek city of Syracuse. Afternoon wandering the island of Ortigia. Fresh seafood dinner at the harbour." },
    { day: 12, title: "Valley of the Temples", description: "Hot air balloon sunrise over Agrigento's Valley of the Temples. Afternoon at a 16th-century wine estate. Farewell dinner." },
    { day: 13, title: "Palermo", description: "Morning transfer to Palermo. Street food tour through the historic markets. Private visit to the Cappella Palatina. Final evening dinner." },
    { day: 14, title: "Departure", description: "Leisurely breakfast. Private transfer to the airport. Arrivederci — until the next journey." },
  ],
  gallery: [
    "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80",
    "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
    "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80",
    "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&q=80",
    "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
  ],
};
