import { Destination, Service, Testimonial, JournalPost, TeamMember, FeaturedJourney } from "./types";

export const destinations: Destination[] = [
  {
    slug: "santorini",
    name: "Santorini",
    region: "Europe",
    tagline: "Where the Aegean Meets the Sky",
    description: "Whitewashed villages perched on volcanic cliffs, sunsets that paint the caldera in gold and amber, and a quietude that only the most discerning travellers will find.",
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=80",
    featured: true,
    duration: "7 Nights",
    startingPrice: "From £4,200 per person",
    includes: ["Boutique cave hotel with caldera views", "Private sunset catamaran cruise", "Wine tasting at Santo Wines", "Guided tour of Oia and Fira", "Daily breakfast & 3 curated dinners", "Private airport transfers"],
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    region: "Asia",
    tagline: "Temples, Tea & Timelessness",
    description: "Ancient temples shrouded in morning mist, private tea ceremonies in hidden gardens, and the gentle rustle of bamboo groves — Kyoto reveals itself slowly to those who linger.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
    featured: true,
    duration: "10 Nights",
    startingPrice: "From £6,800 per person",
    includes: ["Traditional ryokan with private onsen", "Private tea ceremony with a tea master", "Guided bamboo grove & temple walk", "Day trip to Nara with private guide", "Kaiseki dining experiences", "Shinkansen rail passes included"],
  },
  {
    slug: "amalfi-coast",
    name: "Amalfi Coast",
    region: "Europe",
    tagline: "La Dolce Vita, Perfected",
    description: "Terraced lemon groves cascading to cerulean waters, intimate trattorias where the pasta is made by hand, and coastal roads that wind through some of Italy's most breathtaking scenery.",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=1200&q=80",
    featured: true,
    duration: "8 Nights",
    startingPrice: "From £5,500 per person",
    includes: ["Cliffside suite in Ravello or Positano", "Private boat tour to Capri", "Cooking class with a local chef", "Limoncello tasting in Amalfi", "Chauffeured coastal transfers", "Daily breakfast & 4 curated dinners"],
  },
  {
    slug: "patagonia",
    name: "Patagonia",
    region: "South America",
    tagline: "The Edge of the Earth",
    description: "Jagged granite spires rising from pristine wilderness, glacial lakes of impossible blue, and a silence so complete it becomes its own kind of luxury.",
    image: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=1200&q=80",
    featured: true,
    duration: "12 Nights",
    startingPrice: "From £8,900 per person",
    includes: ["Luxury lodge at Torres del Paine", "Guided glacier trekking expedition", "Private estancia stay with gaucho experience", "Perito Moreno glacier boat tour", "All meals & premium wines", "Domestic flights & all transfers"],
  },
  {
    slug: "maldives",
    name: "Maldives",
    region: "Indian Ocean",
    tagline: "Paradise, Reimagined",
    description: "Overwater villas suspended above crystalline lagoons, private sandbanks accessible only by seaplane, and marine life so abundant the reef becomes your living room.",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&q=80",
    featured: true,
    duration: "7 Nights",
    startingPrice: "From £7,200 per person",
    includes: ["Overwater villa with private pool", "Seaplane transfers from Malé", "Sunset dolphin cruise", "Private snorkelling & diving excursions", "Full-board dining at resort restaurants", "Couples spa treatment"],
  },
  {
    slug: "marrakech",
    name: "Marrakech",
    region: "Africa",
    tagline: "A Sensory Tapestry",
    description: "Behind unassuming doors lie palatial riads with mosaic courtyards, rooftop terraces overlooking the Atlas Mountains, and souks that tell stories in saffron and silk.",
    image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1200&q=80",
    featured: true,
    duration: "5 Nights",
    startingPrice: "From £3,400 per person",
    includes: ["Palatial riad in the Medina", "Private souk tour with local guide", "Atlas Mountains day excursion", "Traditional hammam & spa experience", "Rooftop cooking class", "Daily breakfast & 2 curated dinners"],
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    region: "Oceania",
    tagline: "Nature's Masterwork",
    description: "From fjords carved by glaciers to geothermal wonderlands, New Zealand offers an unparalleled canvas of natural beauty paired with world-class lodges and vineyard estates.",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80",
    duration: "14 Nights",
    startingPrice: "From £9,500 per person",
    includes: ["Luxury lodges across both islands", "Milford Sound private cruise", "Helicopter glacier landing", "Vineyard tour in Marlborough", "All domestic flights & transfers", "Daily breakfast & 5 curated dinners"],
  },
  {
    slug: "costa-rica",
    name: "Costa Rica",
    region: "Central America",
    tagline: "Pura Vida in Luxury",
    description: "Cloud forests alive with toucans and orchids, volcanic hot springs nestled in the jungle, and eco-lodges where sustainability meets five-star comfort.",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=1200&q=80",
    duration: "9 Nights",
    startingPrice: "From £5,100 per person",
    includes: ["Eco-luxury treehouse lodge", "Guided cloud forest night walk", "Arenal volcano hot springs", "White-water rafting adventure", "Wildlife safari in Tortuguero", "All transfers & domestic flights"],
  },
  {
    slug: "iceland",
    name: "Iceland",
    region: "Europe",
    tagline: "Fire, Ice & Wonder",
    description: "Where glaciers meet volcanic landscapes, the Northern Lights dance above geothermal pools, and every winding road reveals a waterfall more dramatic than the last.",
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=1200&q=80",
    duration: "8 Nights",
    startingPrice: "From £5,800 per person",
    includes: ["Boutique design hotel in Reykjavík", "Private Golden Circle tour", "Glacier hiking on Sólheimajökull", "Northern Lights hunting excursion", "Blue Lagoon premium access", "South Coast waterfalls & black sand beaches"],
  },
];

export const services: Service[] = [
  {
    title: "Bespoke Itineraries",
    description: "Every journey begins with a conversation. We craft detailed, day-by-day itineraries tailored to your pace, passions, and preferences — from private museum viewings to tables at impossible-to-book restaurants.",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80",
    features: ["Personalised day-by-day planning", "Access to exclusive experiences", "Flexible pacing & preferences", "24/7 concierge support"],
  },
  {
    title: "Luxury Accommodation",
    description: "We maintain relationships with the world's finest hotels, private villas, and boutique properties. Our preferred partner status ensures upgrades, amenities, and the kind of welcome that transforms a stay into a story.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
    features: ["Preferred partner rates & upgrades", "Private villas & estates", "Boutique & heritage properties", "Suite upgrades & VIP amenities"],
  },
  {
    title: "Private Experiences",
    description: "Beyond the guidebook lie experiences that money alone cannot buy. A private dinner in a Tuscan vineyard, a dawn hot-air balloon over Cappadocia, a personal audience with a master artisan — these are the moments we curate.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&q=80",
    features: ["Private guides & historians", "After-hours museum access", "Culinary experiences & cooking classes", "Adventure & wellness retreats"],
  },
  {
    title: "Honeymoons & Celebrations",
    description: "Whether it's a honeymoon, anniversary, or milestone birthday, we design celebrations that honour the occasion with the reverence it deserves. Every detail — from the champagne waiting in your suite to the sunset dinner on a private beach.",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
    features: ["Romantic itinerary design", "Special occasion planning", "Surprise arrangements", "Multi-generational trip coordination"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote: "Vela & Co. didn't just plan our honeymoon — they orchestrated a love letter to Italy. Every detail, from the private water taxi in Venice to the truffle hunting in Piedmont, felt like it was written just for us.",
    author: "Charlotte & James Hartley",
    location: "London, UK",
    trip: "Italian Honeymoon — 14 Days",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
  {
    id: "2",
    quote: "After twenty years of travel, I thought I'd seen it all. Then Vela arranged a private sunrise viewing of Angkor Wat followed by breakfast with a local historian. That morning changed how I see the world.",
    author: "Dr. Michael Chen",
    location: "San Francisco, USA",
    trip: "Southeast Asia — 21 Days",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    id: "3",
    quote: "Planning a family trip with three generations seemed impossible until we found Vela. They created something magical — the grandchildren still talk about the cooking class in Provence, and my mother-in-law hasn't stopped raving about the Loire Valley châteaux.",
    author: "Amara Osei-Bonsu",
    location: "Toronto, Canada",
    trip: "France Multi-Generational — 18 Days",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
  },
  {
    id: "4",
    quote: "The level of access Vela provides is extraordinary. A private after-hours tour of the Uffizi, a personal meeting with a Murano glass master, dinner on a rooftop I didn't know existed. This is travel at its finest.",
    author: "Elizabeth Waverly",
    location: "New York, USA",
    trip: "Art & Culture of Italy — 12 Days",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80",
  },
  {
    id: "5",
    quote: "We asked for adventure, and Vela delivered beyond imagination. Helicopter transfers to a glacier in New Zealand, dawn kayaking in Milford Sound, and a lodge so remote we saw more stars than we knew existed.",
    author: "Henrik & Sofia Lindström",
    location: "Stockholm, Sweden",
    trip: "New Zealand Expedition — 16 Days",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  },
  {
    id: "6",
    quote: "Vela turned our anniversary into a fairy tale. A private dinner in a 16th-century chapel in Ravello, a sunrise hot air balloon over Cappadocia, and a suite in Santorini where the infinity pool seemed to pour into the Aegean. Perfection.",
    author: "Priya & Arjun Mehta",
    location: "Mumbai, India",
    trip: "Mediterranean Anniversary — 12 Days",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
  },
  {
    id: "7",
    quote: "I travel solo, and safety is always top of mind. Vela understood that immediately. Every transfer, every hotel, every guide was vetted and thoughtful. I felt looked after without ever feeling restricted. That's rare.",
    author: "Naomi Adeyemi",
    location: "Lagos, Nigeria",
    trip: "Solo Japan Discovery — 14 Days",
    image: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200&q=80",
  },
  {
    id: "8",
    quote: "The Patagonia trip was unlike anything we've experienced. Vela arranged a private estancia stay, horseback riding through valleys no tourist ever sees, and a glaciologist who made Torres del Paine feel like a living classroom.",
    author: "Marcus & Elena Richter",
    location: "Berlin, Germany",
    trip: "Patagonia Expedition — 10 Days",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  },
  {
    id: "9",
    quote: "We've used Vela three times now, and each trip surpasses the last. The Morocco journey was extraordinary — a private riad, a guide who grew up in the medina, and a desert camp so luxurious I forgot I was in the Sahara.",
    author: "Catherine Beaumont-Hill",
    location: "Sydney, Australia",
    trip: "Morocco Immersion — 11 Days",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
  },
  {
    id: "10",
    quote: "What impressed me most was the follow-up. Three weeks before departure, Isabella called to refine every detail. During the trip, their concierge sorted a last-minute restaurant change in minutes. This is what service should feel like.",
    author: "Jonathan & Claire Park",
    location: "Seoul, South Korea",
    trip: "Tuscan Escape — 8 Days",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
  },
  {
    id: "11",
    quote: "Our children are 6 and 9, and Vela designed a safari that captivated all of us. Junior ranger programmes, bush dinners under the stars, and a guide who made every animal sighting feel like a discovery. The kids are already asking to go back.",
    author: "The Okafor Family",
    location: "Johannesburg, South Africa",
    trip: "East Africa Family Safari — 12 Days",
    image: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=200&q=80",
  },
  {
    id: "12",
    quote: "I'm particular about wine, and Vela knew exactly who to connect me with. Private tastings at estates I'd only read about, a harvest lunch with a fourth-generation winemaker in Barolo, and a cellar tour that ended with a bottle older than me.",
    author: "François Delacroix",
    location: "Paris, France",
    trip: "Italian Wine Tour — 9 Days",
    image: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&q=80",
  },
];

export const journalPosts: JournalPost[] = [
  {
    slug: "art-of-slow-travel",
    title: "The Art of Slow Travel",
    excerpt: "Why the most meaningful journeys are the ones where you linger — and how slowing down reveals a destination's true character.",
    content: `There is a particular quality of light in the late afternoon in Provence that you will never see if you're racing to the next destination. It settles over the lavender fields like liquid gold, turning the stone farmhouses into something from a painting you've seen but can't quite place.\n\nThis is what slow travel offers: not just a place, but a feeling. Not just a photograph, but a memory that lives in your body — the warmth of the sun on your shoulders, the scent of wild thyme, the sound of cicadas marking time in their ancient rhythm.\n\nAt Vela & Co., we've long believed that the best travel experiences aren't measured in destinations visited but in moments truly lived. When we design an itinerary, we build in what we call "white space" — unhurried mornings, spontaneous detours, afternoons with nothing planned but the pleasure of being exactly where you are.\n\nThe art of slow travel isn't about doing less. It's about experiencing more. It's the difference between photographing a cathedral and sitting inside it long enough to watch the light move across the stone floor. It's the difference between visiting a vineyard and spending a morning with the winemaker, learning why this particular hillside produces grapes unlike any other.\n\nOur clients often tell us that their most treasured memories come from these unscripted moments — a conversation with a local shopkeeper, a wrong turn that led to a hidden beach, a rainstorm that drove them into a café where they discovered the best coffee of their lives.`,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    category: "Philosophy",
    date: "2026-06-15",
    readTime: "6 min read",
    author: "Isabella Montague",
  },
  {
    slug: "hidden-gems-japanese-ryokan",
    title: "Hidden Gems: The Japanese Ryokan",
    excerpt: "Beyond the five-star hotels lies a centuries-old tradition of hospitality that redefines what luxury means.",
    content: `The wooden door slides open with a whisper, revealing a world that exists outside of time. Your shoes are gently removed and placed aside. A woman in a perfectly pressed kimono bows and welcomes you not as a guest, but as an honoured visitor to her home.\n\nThis is the ryokan — Japan's gift to the art of hospitality, and perhaps the purest expression of luxury in the world. Not luxury as we've come to define it in the West, with its marble lobbies and crystal chandeliers, but something far more profound: the luxury of attention, of care, of centuries of tradition refined to perfection.\n\nYour room is spare by Western standards — tatami floors, a low table, a futon that will be laid out for you while you bathe. But every element has been chosen with an intentionality that borders on the sacred. The scroll in the alcove was selected for the season. The single flower arrangement captures the essence of the moment.\n\nAnd then there is the onsen. Natural hot springs, often outdoors, where you soak beneath ancient trees as steam rises around you. In winter, snow may fall gently on your shoulders while the water keeps you warm. In autumn, the maple leaves drift across the surface like nature's confetti.`,
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=80",
    category: "Destinations",
    date: "2026-05-28",
    readTime: "8 min read",
    author: "Isabella Montague",
  },
  {
    slug: "sustainable-luxury-new-frontier",
    title: "Sustainable Luxury: The New Frontier",
    excerpt: "How the world's finest properties are proving that environmental responsibility and extraordinary experiences aren't mutually exclusive.",
    content: `There was a time when "eco-lodge" conjured images of composting toilets and cold showers — a noble sacrifice of comfort for conscience. That era is over.\n\nToday's most exciting luxury properties are those that have woven sustainability into the very fabric of the guest experience, not as a compromise but as an elevation. They're proving that the most responsible choice can also be the most remarkable one.\n\nConsider Soneva Fushi in the Maldives, where the "no news, no shoes" philosophy extends to a waste-to-wealth programme that transforms the resort's waste into art, building materials, and biogas. Or Singita in East Africa, where conservation fees directly fund anti-poaching units and community development programmes.\n\nThese properties understand something fundamental: luxury and sustainability aren't opposing forces. They're natural allies. The same attention to detail, the same commitment to excellence, the same desire to create something exceptional — these values serve both pursuits.`,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80",
    category: "Sustainability",
    date: "2026-05-10",
    readTime: "7 min read",
    author: "James Beaumont",
  },
  {
    slug: "perfect-packing-art",
    title: "The Perfect Packing List: An Art Form",
    excerpt: "Our guide to travelling with elegance — what to bring, what to leave behind, and why less truly is more.",
    content: `The way you pack reveals the way you travel. Overpacking speaks to anxiety — the fear that you won't have what you need, that the world beyond your suitcase is somehow insufficient. Underpacking, done well, speaks to confidence and trust.\n\nAfter decades of helping our clients prepare for journeys across every continent, we've refined our approach to packing into something approaching an art form. The principle is simple: bring fewer things, but better things.\n\nStart with a colour palette. Not the rainbow explosion of a tourist's suitcase, but a considered selection of three or four colours that work together. Navy, cream, and a warm accent — terracotta or sage — will carry you from a morning market to an evening dinner without missing a beat.`,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=80",
    category: "Travel Tips",
    date: "2026-04-22",
    readTime: "5 min read",
    author: "James Beaumont",
  },
  {
    slug: "midnight-sun-norway",
    title: "Chasing the Midnight Sun in Norway",
    excerpt: "A journey above the Arctic Circle where the sun never sets and the landscape feels borrowed from another planet.",
    content: `There is something profoundly disorienting about midnight sunlight. The clock reads 11pm, yet the fjord before you is bathed in a golden glow that belongs to late afternoon. Your body says sleep; your eyes say stay.\n\nNorthern Norway in summer is one of those rare places that rewrites your internal clock entirely. The Lofoten Islands, with their dramatic peaks rising straight from the sea, become a photographer's impossible dream — every hour offers a different quality of light, and none of them is darkness.\n\nWe chartered a traditional wooden sailing vessel and spent four days threading between islands that felt like the edge of the known world. Each morning brought a new anchorage, a new village of red-painted fishermen's cabins, a new mountain to hike.\n\nThe silence is what stays with you. Not the absence of sound, but the presence of quiet — the soft lap of Arctic water against the hull, the distant cry of a sea eagle, the whisper of wind through grass that has been growing in this exact spot since the Vikings sailed these same waters.`,
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&q=80",
    category: "Destinations",
    date: "2026-04-08",
    readTime: "6 min read",
    author: "James Beaumont",
  },
  {
    slug: "private-islands-worth-knowing",
    title: "Private Islands Worth Knowing About",
    excerpt: "The world's most exclusive island retreats — and what makes each one irreplaceable.",
    content: `The idea of a private island conjures a very specific fantasy: white sand, turquoise water, absolute solitude. The reality, at the best of them, is far richer than the fantasy.\n\nNorth Island in the Seychelles is perhaps the finest example. Once a coconut plantation left to ruin, it has been painstakingly restored into a conservation sanctuary that happens to include eleven of the most beautiful villas on earth. Giant tortoises wander the grounds. Hawksbill turtles nest on the beaches. The staff-to-guest ratio is approximately ten to one.\n\nThen there is Laucala Island in Fiji, owned by the late Dietrich Mateschitz, where the ethos is "nothing is impossible." A private submarine? Arranged. A four-course dinner on a sandbar that appears only at low tide? Of course. A guided dive on a reef that has never been commercially visited? Simply say when.\n\nBut exclusivity alone does not make an island worth visiting. What separates these properties from mere luxury is intention — a deep commitment to place, to ecology, to creating experiences that couldn't exist anywhere else on earth.`,
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200&q=80",
    category: "Destinations",
    date: "2026-03-25",
    readTime: "7 min read",
    author: "Isabella Montague",
  },
  {
    slug: "wine-regions-beyond-bordeaux",
    title: "Wine Regions Beyond Bordeaux",
    excerpt: "From Georgian qvevri to Sicilian Nerello — the world's most fascinating wine frontiers for the curious palate.",
    content: `Bordeaux is magnificent. Burgundy is transcendent. Napa needs no introduction. But for the genuinely curious wine traveller — the one who has tasted enough to know what they love and enough to want surprise — the real excitement lies elsewhere.\n\nGeorgia may be the most thrilling wine destination on earth right now. Eight thousand years of unbroken winemaking tradition, clay qvevri vessels buried in the earth, and amber wines that taste like nothing you've encountered before. The Kakheti region, with its walnut-tree-shaded courtyards and family supras that last entire afternoons, is wine travel at its most soulful.\n\nSicily's Mount Etna is another revelation. Vines planted on volcanic soil at altitudes that would make most winemakers nervous, producing Nerello Mascalese wines of startling elegance. The contrast between the violence of the volcano and the delicacy of the wine is one of nature's great ironies.\n\nAnd then there is the Swartland in South Africa, where a new generation of winemakers is tearing up the rulebook with old-vine Chenin Blanc and field blends that express a landscape as ancient as any in the wine world.`,
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=1200&q=80",
    category: "Culture",
    date: "2026-03-12",
    readTime: "8 min read",
    author: "Sophie Laurent",
  },
  {
    slug: "architecture-of-escape",
    title: "The Architecture of Escape",
    excerpt: "How the world's most visionary architects are redefining what a hotel can be — and feel like.",
    content: `A great hotel room disappears. You don't think about the ceiling height or the window placement or the angle of the light — you simply feel at ease. The architecture has done its work invisibly, creating a space that holds you without constraining you.\n\nThe best hospitality architects understand this instinctively. Kengo Kuma, whose Aman Kyoto seems to grow from the forest floor, uses timber and stone and moss to blur the boundary between shelter and landscape. You sleep indoors but wake to a view so seamlessly framed that the room feels like a clearing.\n\nIn the deserts of Saudi Arabia, Jean Nouvel's Sharaan resort (still under construction but already legendary) is being carved directly into the sandstone cliffs of AlUla. Not built upon the rock but into it — rooms that are simultaneously ancient and futuristic.\n\nAnd in the Swiss Alps, Peter Zumthor's Therme Vals remains, decades after its completion, the definitive statement on what architecture can do for the body. The thermal baths are carved from locally quarried gneiss, layered like geological strata, lit from above by skylights that frame the sky like minimalist paintings.`,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    category: "Culture",
    date: "2026-02-28",
    readTime: "7 min read",
    author: "Isabella Montague",
  },
  {
    slug: "safari-beyond-the-big-five",
    title: "Safari Beyond the Big Five",
    excerpt: "Why the most memorable wildlife encounters happen when you stop counting and start watching.",
    content: `The Big Five — lion, leopard, elephant, rhino, buffalo — were originally named not for their grandeur but for their difficulty to hunt on foot. That violent origin has been repurposed into a marketing checklist that, while effective, fundamentally misunderstands what makes safari extraordinary.\n\nThe most magical wildlife moments we've witnessed have had nothing to do with size or rarity. A dung beetle rolling its improbable sphere across a dirt road at sunset. A weaver bird constructing its nest with an architect's precision. A baby elephant discovering its trunk for the first time, swinging it with the bewildered delight of a child with a new toy.\n\nThe Okavango Delta in Botswana offers perhaps the richest theatre for these small dramas. Travelling by mokoro — a traditional dugout canoe — through channels barely wider than the boat, you enter a world scaled to intimacy. A malachite kingfisher watches you from a reed stem. A painted reed frog, no larger than a thumbnail, clings to a lily pad.\n\nThis is safari as meditation rather than conquest. And it requires something increasingly rare in modern travel: the willingness to be still.`,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80",
    category: "Destinations",
    date: "2026-02-14",
    readTime: "6 min read",
    author: "James Beaumont",
  },
  {
    slug: "art-of-the-train-journey",
    title: "The Lost Art of the Train Journey",
    excerpt: "From the Orient Express to Japan's Shinkansen — why the journey itself deserves to be the destination.",
    content: `There is a particular pleasure in watching a landscape unfold from a train window that no other form of travel can replicate. Not the compressed geography of a plane, nor the road-level perspective of a car, but something in between — elevated just enough to see the shape of the land, slow enough to register its details.\n\nThe Venice Simplon-Orient-Express remains the gold standard. Not because the route — London to Venice, or Venice to Paris — is inherently remarkable, but because the train itself creates a world so complete, so hermetically luxurious, that the outside scenery becomes a moving backdrop to an interior drama of champagne, white linen, and conversation with strangers who become friends by dessert.\n\nJapan's rail network offers a different kind of poetry. The Shinkansen is not luxurious in the European sense — it is luxurious in its precision, its silence, its absolute reliability. Watching Mount Fuji slide past your window at 300 kilometres per hour while sipping green tea from a bento box is an experience that distils everything beautiful about Japanese culture into a single, fleeting moment.\n\nAnd then there are the slow trains — the Glacier Express in Switzerland, crawling through valleys so pristine they look digitally enhanced, or the Belmond Royal Scotsman, threading through the Highlands with a whisky bar that never closes.`,
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=1200&q=80",
    category: "Philosophy",
    date: "2026-01-30",
    readTime: "7 min read",
    author: "Sophie Laurent",
  },
  {
    slug: "wellness-retreats-that-actually-work",
    title: "Wellness Retreats That Actually Work",
    excerpt: "Cutting through the spa noise to find the places where transformation is real, not just photogenic.",
    content: `The wellness industry has a credibility problem. For every genuinely transformative retreat, there are a dozen that amount to expensive bathrobes and cucumber water in photogenic settings. The challenge for the discerning traveller is separating substance from aesthetics.\n\nSHA Wellness Clinic in Alicante, Spain, is substance incarnate. Founded by a businessman who reversed his own health crisis through macrobiotic nutrition and integrative medicine, SHA employs over 300 medical professionals. This is not a spa with doctors — it is a medical facility that happens to be extraordinarily beautiful.\n\nKamalaya in Koh Samui takes a different approach, rooting its programmes in Traditional Chinese Medicine and Ayurveda. The setting — a former monk's cave overlooking the Gulf of Thailand — sets a tone of genuine contemplation. Their sleep enhancement programme, developed with chronobiologists, has helped executives who haven't slept properly in years.\n\nWhat these places share is seriousness of purpose. They are not selling relaxation as a product but offering health as a practice. The difference becomes apparent on day three, when the superficial calm of arrival gives way to something deeper — a recalibration that you carry home.`,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=1200&q=80",
    category: "Wellness",
    date: "2026-01-15",
    readTime: "6 min read",
    author: "Isabella Montague",
  },
  {
    slug: "culinary-pilgrimages",
    title: "Culinary Pilgrimages: Eating Your Way Through Culture",
    excerpt: "The restaurants, markets, and kitchen tables that justify a journey all on their own.",
    content: `Some trips are built around a single meal. Not metaphorically — literally. A table at Noma in Copenhagen, a kaiseki dinner at Kikunoi in Kyoto, a Sunday asado at Francis Mallmann's island in Patagonia. These are meals that don't accompany a journey; they are the journey.\n\nBut the most memorable food travel often happens away from Michelin stars. In Oaxaca, Mexico, the best mole is served by a grandmother who learned the recipe from her grandmother, in a courtyard where chickens wander between tables. In Bologna, the best tortellini is found not in a restaurant but in the home of a sfoglina — a pasta maker — who rolls sheets of dough so thin you can read a newspaper through them.\n\nWe've built entire itineraries around food moments: a dawn visit to Tokyo's outer market with a retired sushi chef, a truffle hunt in Istria with a man whose dog is better at finding tartufi than any pig, a cheese cave in the Swiss Alps where wheels of Gruyère age in silence for years.\n\nFood travel, done well, is never really about food. It is about the people who make it, the places that shaped them, and the traditions they carry forward with every dish they serve.`,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80",
    category: "Culture",
    date: "2025-12-28",
    readTime: "7 min read",
    author: "Sophie Laurent",
  },
  {
    slug: "photographing-your-journey",
    title: "Photographing Your Journey: A Minimalist Guide",
    excerpt: "How to capture meaningful travel photographs without spending your trip behind a lens.",
    content: `The great paradox of travel photography is this: the more time you spend trying to capture a moment, the less of it you actually experience. We've watched guests miss entire sunsets while adjusting camera settings, and couples so focused on the perfect selfie that they never actually looked at the view behind them.\n\nThe solution isn't to stop photographing — it's to photograph differently. Here is our minimalist approach, refined over years of helping clients document their journeys.\n\nFirst, limit yourself to one device. If you bring a dedicated camera, leave your phone in your pocket. The act of choosing forces intentionality. Second, set a quota: no more than twenty photographs per day. This sounds restrictive until you realise that selectivity produces better images than abundance ever could.\n\nThird, photograph the margins. Not the monument itself but the shadow it casts. Not the market stall but the vendor's hands. Not the view from the terrace but the condensation on your wine glass with the view behind it, slightly blurred. These images, months later, will bring back the feeling of a place in ways that postcard-perfect shots never do.`,
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1200&q=80",
    category: "Travel Tips",
    date: "2025-12-15",
    readTime: "5 min read",
    author: "James Beaumont",
  },
  {
    slug: "winter-destinations-that-transform",
    title: "Winter Destinations That Transform Under Snow",
    excerpt: "The places where cold weather doesn't diminish beauty — it reveals an entirely different kind.",
    content: `There is a bias in luxury travel toward warmth. Beach, sun, blue water — the default palette of escape. But some of the most extraordinary travel experiences on earth require a coat, and the destinations that transform under snow offer a beauty that their summer selves can only hint at.\n\nKyoto in winter is a revelation. The bamboo groves of Arashiyama, heavy with snow, creak and sway in a silence so complete it feels sacred. The golden pavilion of Kinkaku-ji, reflected in a frozen pond, becomes something from a woodblock print. And the ryokans — already magnificent — gain an extra dimension when you can soak in a steaming outdoor onsen while snowflakes melt on your shoulders.\n\nThe Canadian Rockies around Lake Louise offer winter at its most cinematic. The lake freezes to a turquoise mirror, the mountains wear white capes, and the Fairmont Château presides over it all like a castle from a particularly well-funded fairy tale.\n\nAnd then there is Finnish Lapland, where winter isn't a season but a way of life. Staying in a glass igloo under the Northern Lights, being pulled across a frozen lake by a team of huskies, sitting in a smoke sauna heated for eight hours — these are experiences that belong exclusively to the cold.`,
    image: "https://images.unsplash.com/photo-1477601263568-180e2c6d046e?w=1200&q=80",
    category: "Destinations",
    date: "2025-12-01",
    readTime: "7 min read",
    author: "Isabella Montague",
  },
  {
    slug: "travelling-with-purpose",
    title: "Travelling with Purpose: Beyond Voluntourism",
    excerpt: "How meaningful engagement with communities is replacing performative charity — and why it matters.",
    content: `Voluntourism, as traditionally practiced, has a problem. Well-meaning travellers spend a few days painting a school or building a wall, take photographs for social media, and leave — often having displaced local workers who could have done the job better, faster, and with lasting accountability.\n\nThe alternative isn't to disengage. It's to engage differently. Purposeful travel means supporting communities through their own initiatives, on their own terms, with your resources rather than your labour.\n\nIn Rwanda, we partner with a women's cooperative that produces some of the finest coffee in East Africa. Our clients don't pick beans — they sit with the cooperative's founders, learn about their business model, taste coffee at various stages of production, and purchase directly. The experience is educational, the connection is genuine, and the economic impact is real.\n\nIn Peru, we've developed a relationship with a Quechua weaving community in the Sacred Valley. Guests learn traditional dyeing techniques using plants that grow on the mountainside, hear the stories encoded in textile patterns, and commission custom pieces that take months to complete. The exchange is cultural, not charitable — and both sides leave richer for it.`,
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&q=80",
    category: "Sustainability",
    date: "2025-11-18",
    readTime: "8 min read",
    author: "James Beaumont",
  },
];

export const teamMembers: TeamMember[] = [
  {
    name: "Isabella Montague",
    role: "Founder & Lead Advisor",
    bio: "With over two decades in luxury travel, Isabella founded Vela & Co. on a simple belief: that travel, at its best, is a transformative art. A former travel editor and Virtuoso advisor, she brings an editorial eye and an unrivalled network to every journey she crafts.",
    image: "/team/isabella.png",
    linkedin: "https://www.linkedin.com/in/isabella-montague",
  },
  {
    name: "James Beaumont",
    role: "Senior Travel Advisor",
    bio: "James specialises in adventure and expedition travel, from Antarctic cruises to Saharan desert camps. His background in documentary filmmaking gives him an eye for the cinematic — every itinerary he designs reads like a story worth telling.",
    image: "/team/james.png",
    linkedin: "https://www.linkedin.com/in/james-beaumont",
  },
  {
    name: "Sophie Laurent",
    role: "European Specialist",
    bio: "Born in Lyon and educated in Florence, Sophie brings an insider's knowledge of Europe that no guidebook can match. From hidden bistros in Paris to private palazzo tours in Venice, her connections open doors that most travellers never know exist.",
    image: "/team/sophie.png",
    linkedin: "https://www.linkedin.com/in/sophie-laurent",
  },
];

export const featuredJourney: FeaturedJourney = {
  slug: "amalfi-to-sicily",
  title: "The Italian Riviera",
  subtitle: "Amalfi to Sicily — A Journey Through Southern Italy's Soul",
  heroImage: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=1800&q=80",
  duration: "14 Days / 13 Nights",
  startingPrice: "From £12,500 per person",
  highlights: [
    "Private yacht transfer along the Amalfi Coast",
    "Exclusive cooking class with a Michelin-starred chef",
    "After-hours visit to Pompeii with an archaeologist",
    "Wine tasting at a 16th-century Sicilian estate",
    "Hot air balloon sunrise over the Valley of the Temples",
  ],
  description: "This is not a tour of Southern Italy. It is an immersion — a carefully choreographed journey through the landscapes, flavours, and stories that have shaped one of the world's most captivating regions. From the vertiginous beauty of the Amalfi Coast to the wild, untamed spirit of Sicily, every day reveals a new facet of Italy's southern soul.",
  itinerary: [
    { day: 1, title: "Arrival in Naples", description: "Private transfer to your clifftop suite in Ravello. Welcome dinner overlooking the Mediterranean.", image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80" },
    { day: 2, title: "Ravello & Amalfi", description: "Morning visit to Villa Cimbrone's gardens. Afternoon exploration of Amalfi with a local historian. Evening aperitivo at a hidden terrace.", image: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80" },
    { day: 3, title: "Amalfi Coast by Sea", description: "Private yacht along the coast. Stop at a secluded cove for swimming. Lunch at a waterfront restaurant in Positano accessible only by boat." },
    { day: 4, title: "Pompeii & Herculaneum", description: "After-hours private tour of Pompeii with a leading archaeologist. Afternoon visit to the lesser-known Herculaneum." },
    { day: 5, title: "Capri", description: "Day trip to Capri by private boat. Visit the Blue Grotto, explore the Gardens of Augustus, lunch at a cliffside restaurant." },
    { day: 6, title: "Journey to Puglia", description: "Scenic drive through the countryside to Puglia. Settle into a restored masseria. Evening olive oil tasting." },
    { day: 7, title: "Puglia Discoveries", description: "Morning visit to the trulli houses of Alberobello. Afternoon cooking class featuring traditional Puglian cuisine. Dinner under the stars." },
    { day: 8, title: "Matera", description: "Explore the ancient cave dwellings of Matera — a UNESCO World Heritage Site. Private lunch in a converted sassi restaurant." },
    { day: 9, title: "Journey to Sicily", description: "Flight to Catania. Private transfer to Taormina. Evening passeggiata and dinner with views of Mount Etna." },
    { day: 10, title: "Mount Etna", description: "Guided ascent of Europe's most active volcano. Wine tasting at a vineyard on Etna's slopes. Sunset dinner in Taormina." },
    { day: 11, title: "Syracuse & Ortigia", description: "Day exploring the ancient Greek city of Syracuse. Afternoon wandering the island of Ortigia. Fresh seafood dinner at the harbour." },
    { day: 12, title: "Valley of the Temples", description: "Hot air balloon sunrise over Agrigento's Valley of the Temples. Afternoon at a 16th-century wine estate. Farewell dinner." },
    { day: 13, title: "Palermo", description: "Morning transfer to Palermo. Street food tour through the historic markets. Private visit to the Cappella Palatina. Final evening dinner." },
    { day: 14, title: "Departure", description: "Leisurely breakfast. Private transfer to the airport. Arrivederci — until the next journey." },
  ],
  gallery: [
    "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80",
    "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
    "https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80",
    "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&q=80",
    "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
  ],
};
